"""Turn the Phase 9 data layer's Terraform outputs into this phase's two config files.

    make k8s-config HOME_CIDR=203.0.113.7/32 VLLM_TARGET_IP=100.65.15.91

Writes:

* ``deploy/k8s/eksctl/cluster.yaml`` — **committed**. VPC id, the two public subnet ids
  and their availability zones, the data layer's workload security group, and the two
  DynamoDB table ARNs the gateway's IRSA role is scoped to. Identifiers, not credentials:
  the same class of thing ``docs/evidence/p9-aws/01-data-outputs.txt`` already publishes.
* ``deploy/k8s/values.aws.yaml`` — **gitignored**, because it carries the operator's home
  CIDR. Written only when ``--home-cidr`` is given.

**Why a generator rather than a hand-edited file.** ``deploy/aws/compute`` reads the data
layer through ``terraform_remote_state`` and Terraform checks the wiring; a Helm chart and
an eksctl config have no such mechanism, so the coupling would otherwise be a dozen ids
copied by eye at the start of a long session. This script is that wiring, and
``tests/test_deploy_k8s.py`` holds every output it reads to a real ``output`` block in
``deploy/aws/data/outputs.tf`` — the keyless half of the same check
``test_compute_reads_the_data_layer_through_its_published_outputs`` performs for Phase 9.

**It reads local Terraform state and makes no AWS call.** ``terraform output`` opens
``deploy/aws/data/terraform.tfstate`` and nothing else, which is what lets this run under
BUILD_PLAN §0.2 invariant 2 — Claude Code may write config; the human applies it.

Re-run it whenever the data layer is rebuilt, and commit the diff: a ``cluster.yaml``
whose subnet ids belong to a VPC that no longer exists fails at ``eksctl create cluster``,
about fifteen minutes in.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from string import Template
from typing import Any

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
DATA_ROOT = REPO / "deploy" / "aws" / "data"
CLUSTER_YAML = HERE / "eksctl" / "cluster.yaml"
VALUES_YAML = HERE / "values.aws.yaml"

#: The cluster's name, the namespace, and the service account. `headroom` throughout,
#: matching `var.project` in both Terraform roots — which is also what the subnet tag
#: `kubernetes.io/cluster/headroom` names, and what `tests/test_deploy_k8s.py` pins the
#: two files to each other with.
CLUSTER = "headroom"
NAMESPACE = "headroom"
SERVICE_ACCOUNT = "headroom-gateway"

#: Every data-layer output this phase depends on. Held to `deploy/aws/data/outputs.tf` by
#: `test_every_data_layer_output_the_k8s_config_reads_is_one_the_data_layer_publishes`, so
#: a rename on either side fails on the pull request rather than at `eksctl create`.
REQUIRED_OUTPUTS = (
    "region",
    "vpc_id",
    "public_subnet_ids",
    "public_subnet_azs",
    "workload_security_group_id",
    "budgets_table_name",
    "budgets_table_arn",
    "buckets_table_name",
    "buckets_table_arn",
    "gateway_repository_url",
    "ui_repository_url",
)

CLUSTER_TEMPLATE = Template(
    """# The EKS cluster, as eksctl reads it. Two small managed nodes, in the VPC Phase 9 built.
#
# GENERATED by `make k8s-config` from `deploy/aws/data`'s Terraform outputs. Committed, so
# `git diff` after a regeneration is the answer to "is the data layer still the one this
# config was written against". Edit the generator, not this file.
#
# **The human runs `eksctl`** (BUILD_PLAN §0.2 invariant 2). Claude Code writes this file
# and never applies it.
#
# ── Why the cluster goes in the data layer's VPC ──────────────────────────────
# §P10: "RDS/DynamoDB reused from P9's Terraform (don't rebuild the data layer as k8s
# pods) - using managed services from k8s IS the realistic architecture". The gateway's
# pods have to reach an RDS instance in private subnets whose security group admits one
# thing: anything wearing `headroom-workload`. A cluster in its own VPC would need peering
# or a publicly addressable database; a cluster in *this* VPC needs `attachIDs` below.
#
# ── Why the nodes are in PUBLIC subnets ───────────────────────────────────────
# H-075, inherited unchanged: there is no NAT gateway, because a NAT gateway is $$1.08/day
# on a stack whose whole point is that it is cheap. The private subnets therefore have no
# default route, and a node in one could not pull an image from ECR or reach the EKS API.
# Public subnets with a public IP and a security group that admits only what it must is
# the same trade Phase 9's Fargate tasks took.
#
# ── What is deliberately NOT here ─────────────────────────────────────────────
# * No `version:` — eksctl uses whatever EKS currently defaults to, which is always a
#   version that exists. A number pinned here would be a number nobody re-checks, and the
#   runbook captures `kubectl version` into the evidence so the run says what it ran on.
# * No control-plane logging. `cloudWatch.clusterLogging.enableTypes: []` is explicit
#   rather than absent: five log streams at CloudWatch ingest rates, for three days, to
#   answer questions this phase does not ask.
# * No Cluster Autoscaler, no Karpenter, no metrics-server. The node group is two fixed
#   nodes; see the chart's `autoscaling` block for why the HPA ships off.

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: $cluster
  region: $region
  # The same four cost-allocation keys both Terraform roots apply through `default_tags`
  # (H-080). `Layer: compute` because this cluster is the ephemeral half; the data layer
  # keeps `Layer: data` and `Phase: p9`, which is what lets Cost Explorer answer "what did
  # the data layer cost me while the cluster was up" — the number A7's estimate-versus-
  # actual table needs.
  tags:
    Project: $cluster
    Layer: compute
    Phase: p10
    ManagedBy: eksctl

vpc:
  id: $vpc_id
  subnets:
    public:
$subnet_block
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

iam:
  # The OIDC provider, and the one role a pod in this cluster assumes. This is the EKS
  # spelling of `aws_iam_role.gateway_task` in `deploy/aws/compute/iam.tf`, and it carries
  # the same permissions for the same reason: DynamoDB on exactly two tables, and nothing
  # else. No secrets (the three credentials arrive as a Kubernetes Secret), no logs, no
  # ECR — the node role covers what the kubelet needs.
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: $service_account
        namespace: $namespace
        labels:
          app.kubernetes.io/part-of: headroom
      attachPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: TheBudgetGateAndTheTokenBuckets
            Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
              - dynamodb:Scan
            Resource:
              - $budgets_table_arn
              - $buckets_table_arn
          - Sid: EnsureTableStaysTheSameCodePathItIsLocally
            # `DescribeTable` is what `DynamoClient.ensure_table` calls on every cold
            # client. `CreateTable` is granted and scoped to these two ARNs for the reason
            # `deploy/aws/compute/iam.tf` gives: a permission the shipped code would need
            # is part of the code path, and the path is supposed to be unchanged. It
            # should never fire - Terraform made both tables in Phase 9.
            Effect: Allow
            Action:
              - dynamodb:DescribeTable
              - dynamodb:CreateTable
            Resource:
              - $budgets_table_arn
              - $buckets_table_arn

managedNodeGroups:
  - name: $cluster-nodes
    # t3.medium: 2 vCPU, 4 GiB. The smallest instance that holds two gateway pods plus the
    # surge pod of a rolling upgrade with room for the kubelet and the CNI - which
    # `tests/test_deploy_k8s.py` checks arithmetically against the chart's resource
    # requests, because a Deployment whose pods do not fit sits in Pending with nothing
    # red anywhere.
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    volumeSize: 20
    volumeType: gp3
    # Public subnets, public IPs. See the header: there is no NAT gateway.
    privateNetworking: false
    securityGroups:
      # The data layer's `headroom-workload` group. With the AWS VPC CNI a pod's ENI
      # inherits its node's security groups, so attaching it here is what lets a gateway
      # pod open a connection to RDS - and it is a *membership*, so nothing in the data
      # root names anything in this cluster and `terraform destroy` on the data layer at
      # the end of this phase has nothing to trip over (H-074).
      attachIDs:
        - $workload_security_group_id
    labels:
      role: headroom
    tags:
      Project: $cluster
      Layer: compute
      Phase: p10
      ManagedBy: eksctl

cloudWatch:
  clusterLogging:
    enableTypes: []
"""
)

VALUES_TEMPLATE = Template("""# The AWS half of the chart's values.
#
# GENERATED by `make k8s-config`. **Gitignored** - it carries `$$HOME_CIDR`, the operator's
# home address, for the same reason `deploy/aws/compute/terraform.tfvars` is gitignored.
# Regenerate rather than edit; a home address changes.
#
#     helm upgrade --install headroom deploy/k8s/headroom \\
#       -n $namespace -f deploy/k8s/values.aws.yaml
#
# No credential is in here and none can be: the chart has no field to put one in, and
# `values.schema.json` refuses any key it does not know (BUILD_PLAN §0.2 invariant 3). The
# three secrets arrive in a Kubernetes Secret the operator creates by hand from Secrets
# Manager - deploy/k8s/README.md section 3.

image:
  repository: $gateway_repository_url
  tag: $gateway_tag

aws:
  region: $region
  budgetsTable: $budgets_table_name
  bucketsTable: $buckets_table_name

gateway:
  service:
    # The cluster's front door, and the equivalent of Phase 9's ALB: one internet-facing
    # load balancer, one source address, on the port compose publishes.
    type: LoadBalancer
    port: 8080
    loadBalancerSourceRanges:
      - $home_cidr
    annotations:
      # A Network Load Balancer with instance targets, provisioned by the cloud controller
      # manager EKS already runs. No AWS Load Balancer Controller, no CRDs, no second IAM
      # role, no extra Helm release - and with `externalTrafficPolicy: Cluster` the load
      # balancer's targets are the *nodes*, which do not change while pods are replaced.
      # That is the property the zero-dropped-requests demo rests on.
      #
      # To move to the AWS Load Balancer Controller instead, install it and replace this
      # block with `aws-load-balancer-type: external` plus `-nlb-target-type: ip`. It is a
      # values edit, deliberately: no template mentions AWS.
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

ui:
  image:
    repository: $ui_repository_url
    tag: $ui_tag

vllm:
  # The tailscale egress proxy: how a pod in $region reaches the two 4090s on the
  # operator's desk. `$vllm_target_ip` is the tailnet address of the machine running them
  # (`tailscale status`). The auth key is a Secret, created by hand - README section 3.
  enabled: $vllm_enabled
  targetIP: "$vllm_target_ip"
""")


def terraform_output() -> dict[str, Any]:
    """`terraform output -json` from the data root. Local state; no AWS call."""
    if not (DATA_ROOT / "terraform.tfstate").exists():
        sys.exit(
            f"no Terraform state at {DATA_ROOT / 'terraform.tfstate'}.\n"
            "The Phase 9 data layer is what this reads. If it has been destroyed, this "
            "phase has nothing to deploy against; if it is on another machine, generate "
            "there. deploy/aws/README.md section 2."
        )
    result = subprocess.run(
        ["terraform", f"-chdir={DATA_ROOT}", "output", "-json"],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        sys.exit(f"terraform output failed:\n{result.stderr.strip()}")
    raw: dict[str, Any] = json.loads(result.stdout)
    values = {name: entry["value"] for name, entry in raw.items()}

    missing = [name for name in REQUIRED_OUTPUTS if name not in values]
    if missing:
        sys.exit(
            f"the data layer publishes no {', '.join(missing)}.\n"
            "`public_subnet_azs` arrives with the subnet tags this phase adds: run "
            "`terraform -chdir=deploy/aws/data apply` first (deploy/k8s/README.md "
            "section 2)."
        )
    return values


def subnet_block(subnet_ids: list[str], azs: list[str]) -> str:
    """`vpc.subnets.public`, keyed by availability zone.

    Keyed by AZ rather than by an arbitrary name because that is the form every eksctl
    example uses and the form its own validation is friendliest about. The zones come from
    Terraform rather than from a `describe-subnets` call, which is what keeps this script
    keyless.
    """
    if len(subnet_ids) != len(azs):
        sys.exit(f"the data layer published {len(subnet_ids)} subnets and {len(azs)} zones")
    pairs = zip(azs, subnet_ids, strict=True)
    return "\n".join(f"      {az}:\n        id: {sid}" for az, sid in pairs)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="render_config", description=__doc__)
    parser.add_argument(
        "--home-cidr",
        help="the only address the gateway's load balancer will admit, e.g. 203.0.113.7/32. "
        "`curl -s https://checkip.amazonaws.com` prints the address. Omit to write only "
        "the eksctl config.",
    )
    parser.add_argument(
        "--vllm-target-ip",
        default="",
        help="tailnet address of the machine running the two vLLM containers "
        "(`tailscale status`). Omit and the chart is rendered with vllm.enabled=false.",
    )
    parser.add_argument("--gateway-tag", default="latest", help="gateway image tag in ECR")
    parser.add_argument("--ui-tag", default="latest", help="console image tag in ECR")
    args = parser.parse_args(argv)

    if args.home_cidr == "0.0.0.0/0":
        sys.exit(
            "refusing 0.0.0.0/0: the gateway's load balancer fronts the admin API. "
            "`deploy/aws/compute/variables.tf` refuses the same value for the same reason."
        )

    out = terraform_output()

    CLUSTER_YAML.parent.mkdir(parents=True, exist_ok=True)
    CLUSTER_YAML.write_text(
        CLUSTER_TEMPLATE.substitute(
            cluster=CLUSTER,
            namespace=NAMESPACE,
            service_account=SERVICE_ACCOUNT,
            region=out["region"],
            vpc_id=out["vpc_id"],
            subnet_block=subnet_block(out["public_subnet_ids"], out["public_subnet_azs"]),
            workload_security_group_id=out["workload_security_group_id"],
            budgets_table_arn=out["budgets_table_arn"],
            buckets_table_arn=out["buckets_table_arn"],
        ),
        encoding="utf-8",
    )
    print(f"wrote {CLUSTER_YAML.relative_to(REPO)}")

    if not args.home_cidr:
        print(
            "no --home-cidr, so deploy/k8s/values.aws.yaml was not written. "
            'Pass HOME_CIDR="$(curl -s https://checkip.amazonaws.com)/32" to make.'
        )
        return 0

    VALUES_YAML.write_text(
        VALUES_TEMPLATE.substitute(
            namespace=NAMESPACE,
            region=out["region"],
            gateway_repository_url=out["gateway_repository_url"],
            gateway_tag=args.gateway_tag,
            ui_repository_url=out["ui_repository_url"],
            ui_tag=args.ui_tag,
            budgets_table_name=out["budgets_table_name"],
            buckets_table_name=out["buckets_table_name"],
            home_cidr=args.home_cidr,
            vllm_enabled="true" if args.vllm_target_ip else "false",
            vllm_target_ip=args.vllm_target_ip,
        ),
        encoding="utf-8",
    )
    print(f"wrote {VALUES_YAML.relative_to(REPO)}  (gitignored: it carries {args.home_cidr})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
