"""Reading the committed semantic corpus, and the embedder the keyless suite runs on.

The corpus itself is generated by :mod:`tests.support.build_semantic_corpus` on a
machine with the ``embed`` extra; this module is what the suite uses to read it back.

**The embedder here is a two-space hybrid, and that is deliberate rather than sloppy.**
:class:`CorpusEmbedder` returns the *real* ``bge-small-en-v1.5`` vector for any text in
the committed corpus and a deterministic hashed vector for anything else. So:

* every assertion about **similarity** — a paraphrase hits, a near-miss misses, where the
  threshold has to sit — is made against numbers a real model produced, in CI, with no
  torch installed;
* every other test in the suite (eligibility, isolation, poisoning, replay, the ledger)
  embeds arbitrary invented text and gets a stable vector rather than an error.

The two spaces do not interfere: a hashed vector and a model vector are near-orthogonal,
which ``tests/test_embedding.py`` asserts rather than assumes. What this must never
become is a *production* fallback — a gateway that silently swapped models would keep
serving hits from a namespace that no longer means what it says. Production resolves one
embedder by name and fails loudly if it cannot load it
(``headroom/cache/embedding.py``); this class exists only under ``tests/``.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any, Final

from headroom.cache.embedding import Embedder, HashingEmbedder

__all__ = [
    "CORPUS_PATH",
    "EMBEDDING_DIMENSIONS",
    "EMBEDDING_MODEL",
    "FLOAT_PLACES",
    "Corpus",
    "CorpusEmbedder",
    "corpus_hash",
    "load_corpus",
]

#: BUILD_PLAN L6's model, named here so the generator, the fixture, and the assertions
#: about what the fixture *is* all read it from one place.
EMBEDDING_MODEL: Final = "BAAI/bge-small-en-v1.5"
EMBEDDING_DIMENSIONS: Final = 384
FLOAT_PLACES: Final = 6

CORPUS_PATH: Final = Path(__file__).resolve().parents[1] / "fixtures" / "semantic_corpus.json"


def corpus_hash(payload: dict[str, Any]) -> str:
    """A content hash over the corpus's **texts and provenance**, not its vectors.

    Vectors are an artifact of the model; the texts and the source-question mapping are
    the corpus. Hashing the former would make a rounding change look like a corpus
    change, and hashing the latter is what pins the thing a reader has to trust: that
    every probe still names the question it is a paraphrase of.
    """
    material = {
        "embedding_model": payload["embedding_model"],
        "questions": [
            {key: row[key] for key in ("id", "template", "artist", "text", "answer")}
            for row in payload["questions"]
        ],
        "probes": [
            {key: row[key] for key in ("id", "source", "template", "artist", "text")}
            for row in payload["probes"]
        ],
    }
    canonical = json.dumps(material, sort_keys=True, ensure_ascii=False, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


@dataclass(frozen=True, slots=True)
class CorpusRow:
    """One text with its committed vector and its provenance."""

    id: str
    text: str
    vector: tuple[float, ...]
    template: str
    artist: str
    #: For a probe, the question it paraphrases. For a question, itself.
    source: str
    answer: str | None = None


@dataclass(frozen=True, slots=True)
class Corpus:
    """The committed corpus: canonical questions, their probes, and the vectors."""

    embedding_model: str
    dimensions: int
    corpus_hash: str
    questions: tuple[CorpusRow, ...]
    probes: tuple[CorpusRow, ...]

    @property
    def rows(self) -> tuple[CorpusRow, ...]:
        return self.questions + self.probes

    def question(self, question_id: str) -> CorpusRow:
        for row in self.questions:
            if row.id == question_id:
                return row
        raise KeyError(question_id)

    def vectors(self) -> dict[str, tuple[float, ...]]:
        """text -> vector, which is what :class:`CorpusEmbedder` looks up."""
        return {row.text: row.vector for row in self.rows}


@lru_cache(maxsize=1)
def load_corpus() -> Corpus:
    """Read and validate the committed fixture. Cached: it is read by many tests."""
    payload = json.loads(CORPUS_PATH.read_text(encoding="utf-8"))
    questions = tuple(
        CorpusRow(
            id=row["id"],
            text=row["text"],
            vector=tuple(row["vector"]),
            template=row["template"],
            artist=row["artist"],
            source=row["id"],
            answer=row["answer"],
        )
        for row in payload["questions"]
    )
    probes = tuple(
        CorpusRow(
            id=row["id"],
            text=row["text"],
            vector=tuple(row["vector"]),
            template=row["template"],
            artist=row["artist"],
            source=row["source"],
        )
        for row in payload["probes"]
    )
    return Corpus(
        embedding_model=payload["embedding_model"],
        dimensions=payload["dimensions"],
        corpus_hash=payload["corpus_hash"],
        questions=questions,
        probes=probes,
    )


class CorpusEmbedder:
    """Real committed vectors for corpus texts, deterministic hashed ones for the rest.

    Carries the corpus's own model id, because the model id is part of the semantic
    cache's namespace: an entry embedded by one model must never be matched against a
    query embedded by another, and the tests inherit that property rather than opting
    out of it.
    """

    __slots__ = ("_fallback", "_vectors", "calls", "dimensions", "model_id")

    def __init__(self) -> None:
        corpus = load_corpus()
        self.model_id = corpus.embedding_model
        self.dimensions = corpus.dimensions
        self._vectors = corpus.vectors()
        self._fallback = HashingEmbedder(dimensions=corpus.dimensions)
        #: How many texts this embedder was asked to encode. The disabled-tenant proof
        #: reads it: "no embedding compute" has to be a measurement, not a claim.
        self.calls = 0

    def embed(self, texts: list[str]) -> list[list[float]]:
        self.calls += len(texts)
        unknown = [text for text in texts if text not in self._vectors]
        hashed = dict(zip(unknown, self._fallback.embed(unknown), strict=True)) if unknown else {}
        return [
            list(self._vectors[text]) if text in self._vectors else hashed[text] for text in texts
        ]

    def resolve(self) -> Embedder:
        """Already loaded: the vectors are a committed file and the fallback is arithmetic.

        Present so this satisfies :class:`~headroom.cache.embedding.CacheEmbedder` and can
        be injected wherever the gateway expects one — including through
        ``PUT /admin/cache``'s probe, which therefore succeeds in the suite for the honest
        reason that there really is nothing left to load.
        """
        return self

    def load(self) -> None:
        """Nothing to load. See :meth:`resolve`."""
